# Generated by Django 3.2.8 on 2023-02-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_users', '0002_notesuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesuser',
            name='birthday_year',
            field=models.PositiveIntegerField(default=1984),
        ),
    ]
